### ISSUE TITLE
Authentication URL is not working.

### ISSUE THREAD

**Issue by kaladay** [TAMULib/SAGE#465]
**Describe the bug**
When using the URL `https://labs.library.tamu.edu/authfix`, the authentication does not fully complete and returns an error. This then causes a separate problem identified and solved in https://github.com/TAMULib/Weaver-UI-Core/pull/218.

This is either a bug in the server and not something solvable by code or a bug in the processing code. Determine where the problem is and go from there.

**To Reproduce**
1. Set `AUTH_SERVICE_URL=https://labs.library.tamu.edu/authfix` on a project, such as SAGE.
2. Start docker.
3. Attempt to login.

**Expected behavior**
If the error is valid, then do nothing and the problem needs to be sovled on the server providing the service. If the error is invalid, then there should be no error.

**Comment by jcreel** [comment]
Check configuration to ensure we are pointing at the new auth service.

**Comment by wwelling** [comment]
Default for running locally is up to date:
https://github.com/TAMULib/SAGE/blob/main/.wvr/build-config.js#L40

Default for running using docker compose is up to date:
https://github.com/TAMULib/SAGE/blob/main/example.env#L28

Default for build docker image will use an auth URL without specifying version in path:
https://github.com/TAMULib/SAGE/blob/main/Dockerfile#L98

I think this is all acceptable and the error indicated above when unable to reach a valid auth service is appropriate. It may be that the frontend error could be more informative, and another issue may be necessary.

This issue is resolved by DevOps using appropriate auth URL to deploy.

**Comment by kaladay** [comment]
You missed a spot:
- https://github.com/TAMULib/SAGE/blob/ec84fca9edacbfc9edfe7dbb61661a8d5e53100b/DEPLOYING.md

The authfix there needs to be updated.

**Comment by wwelling** [comment]
@kaladay good catch. As not functional, should still be updated. Will do global search next time. ;)
